### PR TITLE
Network -> LigandNetwork

### PR DESCRIPTION
**Pull request by dotsdl**
Changes to accommodate recent changes in `openfe`: https://github.com/OpenFreeEnergy/openfe/commit/e30864c557e2452c8a1b9dc6a7ecd00ed58960e3

### CODE REVIEW

**Review by IAlibay — CHANGES_REQUESTED** [review]
Sorry I'm going to have to block this until the next gufe release is out. Unfortunately openfe-benchmarks is partially user facing at the moment, so I can't ask folks to update to an unreleased branch.

**Comment by dotsdl** [comment]
No worries, I'll keep using this branch as a band-aid for tests in `alchemiscale`.

**Comment by IAlibay** [comment]
Not sure if `cannot import name 'SmallMoleculeComponent' from 'openfe.setup'` is down to openfe not having sufficiently updated?

**Comment by dotsdl** [comment]
Not sure what's broken here currently, but I have at least the imports fixed AFAICT. Looks like some interaction with the OpenFF Toolkit may be busted?

**Comment by IAlibay** [comment]
> Not sure what's broken here currently, but I have at least the imports fixed AFAICT. Looks like some interaction with the OpenFF Toolkit may be busted?

I suspect this is down to the latest openfe & gufe not being compatible with off-tk<0.11?

**Pull request merged**
